### ISSUE TITLE
Lazarus 2.2.0-RC1

### ISSUE THREAD

**Issue by JordanL2** [flathub/org.freedesktop.Sdk.Extension.freepascal#2]
Do we need to wait for Lazarus 2.2 to hit stable before we can update this SDK to use it, or can we update this to use the RC?

I ask because it contains a fix for Qt5 interfaces with Wayland, Qt5 applications built with Lazarus 2.0.12 don't start on Wayland.
```
[FORMS.PP] ExceptionOccurred
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000631083
  $000000000060FED9
  $000000000079538D
  $0000000000794D6D
  $0000000000790EA3
  $000000000069DE91
  $000000000069DDAB
  $000000000047B6AA
  $000000000044B870
  $000000000043A21C
[FORMS.PP] ExceptionOccurred
```

If we have to wait then we have to wait, since release is probably ~3-4 months away I thought I'd ask.

**Comment by catsout** [comment]
It's sad that I haven't do any pascal programing.  
Other sdks like java,rust solve this by creating a separate repo like `openjdk-8` or `rust-nightly`.  

Currently only [peazip](https://github.com/flathub/io.github.peazip.PeaZip) use this, 
if you want to make this repo use rc version, need to check peazip works on rc version

So could you build peazip and `build-bundle` to a single file and send to me through `google driver or mega`?
As these days I can only go online via limited cellular data, pulling down a new sdk can be difficult for me.

**Comment by JordanL2** [comment]
Ok, I've made the flatpak bundle, how do I send it to you via google drive?

My gmail address is jordanleppert@gmail.com

**Comment by hfiguiere** [comment]
> I ask because it contains a fix for Qt5 interfaces with Wayland, Qt5 applications built with Lazarus 2.0.12 don't start on Wayland.

Not even using X11? If they are flatpak you can just force X11.

**Comment by JordanL2** [comment]
> > I ask because it contains a fix for Qt5 interfaces with Wayland, Qt5 applications built with Lazarus 2.0.12 don't start on Wayland.
> 
> Not even using X11? If they are flatpak you can just force X11.

Oh sure, it works via Xwayland, just not natively.

**Comment by JordanL2** [comment]
BTW I opened this PR to propose this update:
https://github.com/flathub/org.freedesktop.Sdk.Extension.freepascal/pull/3

**Comment by catsout** [comment]
The gmail limit file size to 25M.  
So I think you can just send it to me through email.  
email: outline941@live.com
